default:
  image: zhanghx0905/rcore-ci

stages:
  - test

test-code-job:
  stage: test
  script:
    - git clone https://gitlab-ci-token:m6jdCmKSw8wqpG2sjasQ@git.tsinghua.edu.cn/os-21a/rcore-tutorial-ci.git ci-user
    - cd ci-user && make test CHAPTER=`echo $CI_COMMIT_REF_NAME | grep -oP 'ch\K[0-9]'`

